name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    name: Release Drafter
    environment: release-drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Update version files
        run: |
          sed -i "s/\"version\": .*/\"version\": \"${{ steps.drafter.outputs.resolved_version }}\",/g" library.json
          sed -i "s/esp-audio-libs VERSION .*)/esp-audio-libs VERSION ${{ steps.drafter.outputs.resolved_version }})/g" CMakeLists.txt

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config --global user.name "esphomebot"
            git config --global user.email "68923041+esphomebot@users.noreply.github.com"
            git commit -am "Bump version to ${{ steps.drafter.outputs.resolved_version }}"
            git push
          fi
